"""initial schema

Revision ID: 1af1cd02533d
Revises: 
Create Date: 2026-04-26 13:14:12.592635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af1cd02533d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('max_discount_pct', sa.Float(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('quiet_hours', sa.JSON(), nullable=True),
    sa.Column('budget_daily_eur', sa.Float(), nullable=True),
    sa.Column('product_categories', sa.JSON(), nullable=True),
    sa.Column('min_order_eur', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('offers',
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('discount_text', sa.String(), nullable=True),
    sa.Column('valid_minutes', sa.Integer(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('visuals', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('qr_data', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('discount_eur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('redemption_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('discount_applied_eur', sa.Float(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redemption_records')
    op.drop_table('tokens')
    op.drop_table('offers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
